dataset_parameters:
    testdir: "../datasets/the_simpson_dataset/test"
    traindir: "../datasets/the_simpson_dataset/train"

model_parameters:
    weight_decay: 0.001
    dropout_rate: 0.1
  
    
training_parameters:
  batch_size: 64
  learning_rate: 0.003
  num_epochs: 40

output_parameters:
    part_of_partitions: 3
    out_model_directory: "model/"
    out_graphics_directory: "graphics/"
    out_inference_directory: "inference/"
    