dataset_parameters:
    rootdir: "simpsons_dataset"

model_parameters:
    weight_decay: 0.006
    dropout_rate: 0.2
  
    
training_parameters:
  batch_size: 128
  learning_rate: 0.008
  num_epochs: 20
  k_prop: 0.8

output_parameters:
    part_of_partitions: 4
    out_model_directory: "model/"
    out_graphics_directory: "graphics/"
    out_inference_directory: "inference/"
    