dataset_parameters:
    rootdir: "simpsons_dataset/"

model_parameters:
    weight_decay: 0.09
    dropout_rate: 0.2
  
    
training_parameters:
  batch_size: 32
  learning_rate: 0.008
  num_epochs: 15
  k_prop: 0.8

output_parameters:
    part_of_partitions: 1
    out_model_directory: "model/"
    out_graphics_directory: "graphics/"
    out_inference_directory: "inference/"
    